"""Migration for main

Revision ID: 7acc77db1362
Revises: f247a2df6e6e
Create Date: 2024-03-10 16:14:18.558264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7acc77db1362'
down_revision = 'f247a2df6e6e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
