"""Refactored joinservice and joinAPI, creating new migration just in case.

Revision ID: b631d887d012
Revises: 97c46c16695b
Create Date: 2024-03-13 00:23:05.391380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b631d887d012'
down_revision = '97c46c16695b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
